### ISSUE TITLE
VirtualHost ?

### ISSUE THREAD

**Issue by Sevenn83** [bronycub/sugarcub#1]
Je ne connais pas vraiment Django.

Mais une question me turlupine, sachant que la bestiole tourne sous python, comment allez vous faire pour faire tourner plusieurs instances du site sur une même machine ?

Avec un framework php, les virtuals hosts fonctionne très bien. Mais sous Django ?

**Comment by ghost** [comment]
Bah php c'est juste un cas particulier de CGI, de scripts/programme exécuté par le serveur web pour générer des pages qui ne sont pas directement en html.
Conrètement le serveur appelle php sur les pages en question, qui renvoie le code qui est envoyé par le serveur web, mais rien n'empeche de lui dire "pour les .py, tu lance python <fichier> au lieu de php <fichier>". après la configuration dépend du serveur web en question, ce n'est qu'un cas général ici.

**Comment by mdevlamynck** [comment]
C'est pareil, tu fais tourner plusieurs instances et ton serveur web 
fait la redirection.

En général sur en php avec apache on utilise un mod pour qu'apache sache 
lire le php. Il arrive parfois qu'on fasse tourner un serveur local qui 
exécute le php et apache sert juste de proxy (typiquement ce qu'on 
ferait avec nginx).

Dans le cas de django la solution que je retiens est la seconde (avec le 
serveur local gunicorn) même si la première est aussi possible. Le 
défaut du mod avec python c'est qu'il faut redémarrer le serveur pour 
prendre en compte les modifs dans le code. Avec un serveur local, on 
peut le redémarrer sans rien impacter d'autre, et on peut découper les 
droits d'administration du serveur plus précisement. Par exemple un 
admin système va pas te donner accès au apache, par contre il peut te 
laisser pleinement le contrôle de ton gunicorn.

**Comment by ghost** [comment]
Ah bah désolé du doublon XD (ps: nginx c'est le bien!! c'est le pied à configurer par rapport à apache)

**Comment by mdevlamynck** [comment]
Pour les discussions sur sugarcub, je t'oriente plus vers le répo "officiel". Celui-ci est plus un mirroir.

https://gitlab.com/mdevlamynck/sugarcub

**Comment by Sevenn83** [comment]
Je vois, donc il n'y a pas de problème.
Ps : En plus d'être pas trop chiant sur la configuration Nginx est très performant.
